/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univs.edu.telas;

import univs.edu.ticket.Ticket;
import univs.edu.ticket.TicketDAO;
import univs.edu.usuario.UsuarioAjudado;
import univs.edu.usuario.UsuarioDAO;

/**
 *
 * @author LABORATORIO 01
 */
public class TelaTicketEditar extends javax.swing.JFrame {

    /**
     * Creates new form TelaTicket
     */
    public TelaTicketEditar() {
        initComponents();
        
        
    }
    UsuarioAjudado usuario = new UsuarioAjudado();
        UsuarioDAO dao = new UsuarioDAO();
        Ticket ticket = new Ticket();
        TicketDAO ticketDAO = new TicketDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        tfAssunto = new javax.swing.JTextField();
        Enviar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfMensagem = new javax.swing.JTextArea();
        Assunto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jAnsiedade = new javax.swing.JRadioButton();
        jDrepressao = new javax.swing.JRadioButton();
        rOutros = new javax.swing.JRadioButton();
        tfOutros = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfContato = new javax.swing.JTextField();
        Assunto1 = new javax.swing.JLabel();
        jContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Enviar1.setBackground(new java.awt.Color(51, 153, 255));
        Enviar1.setForeground(new java.awt.Color(255, 255, 255));
        Enviar1.setText("Enviar");
        Enviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar1ActionPerformed(evt);
            }
        });

        tfMensagem.setColumns(20);
        tfMensagem.setRows(5);
        tfMensagem.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tfMensagemCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfMensagemInputMethodTextChanged(evt);
            }
        });
        tfMensagem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfMensagemPropertyChange(evt);
            }
        });
        tfMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMensagemKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tfMensagem);

        Assunto.setForeground(new java.awt.Color(51, 153, 255));
        Assunto.setText("Assunto");

        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Mensagem");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jAnsiedade.setForeground(new java.awt.Color(51, 153, 255));
        jAnsiedade.setText("Ansiedade");
        jAnsiedade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAnsiedadeMouseClicked(evt);
            }
        });
        jAnsiedade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnsiedadeActionPerformed(evt);
            }
        });

        jDrepressao.setForeground(new java.awt.Color(51, 153, 255));
        jDrepressao.setText("Depressão");
        jDrepressao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDrepressaoMouseClicked(evt);
            }
        });
        jDrepressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrepressaoActionPerformed(evt);
            }
        });

        rOutros.setForeground(new java.awt.Color(51, 153, 255));
        rOutros.setText("Outros");
        rOutros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rOutrosMouseClicked(evt);
            }
        });
        rOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rOutrosActionPerformed(evt);
            }
        });

        tfOutros.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Selecione sua situação:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Editar ticket");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phoenix Corporation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        tfContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContatoActionPerformed(evt);
            }
        });

        Assunto1.setForeground(new java.awt.Color(51, 153, 255));
        Assunto1.setText("Contato (Telefone, E-mail, etc)");

        jContador.setText("jLabel5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Assunto1)
                    .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Assunto)
                    .addComponent(jAnsiedade)
                    .addComponent(jDrepressao)
                    .addComponent(jLabel2)
                    .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jContador))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(rOutros)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Enviar1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Assunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jContador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAnsiedade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDrepressao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rOutros)
                    .addComponent(tfOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Assunto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Enviar1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Enviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar1ActionPerformed
        if (!tfMensagem.getText().equals("")) {
            ticket.setMensagem(tfMensagem.getText());
            ticket.setAssunto(tfAssunto.getText());
            ticket.setUsuario(UsuarioAjudado.usuario);
            if (tfContato.getText().isEmpty()) {
                ticket.setCttAj(null);
            } else {
                ticket.setCttAj(tfContato.getText());
            }
            if (rOutros.isSelected()) {
                ticket.setProblema(tfOutros.getText());
            }
            ticketDAO.editar(ticket);
        }
        dispose();
    }//GEN-LAST:event_Enviar1ActionPerformed

    private void tfMensagemCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfMensagemCaretPositionChanged

    }//GEN-LAST:event_tfMensagemCaretPositionChanged

    private void tfMensagemInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfMensagemInputMethodTextChanged

    }//GEN-LAST:event_tfMensagemInputMethodTextChanged

    private void tfMensagemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfMensagemPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMensagemPropertyChange

    private void tfMensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMensagemKeyPressed

        jContador.setText(tfMensagem.getText().length() + "/2000");
    }//GEN-LAST:event_tfMensagemKeyPressed

    private void jAnsiedadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAnsiedadeMouseClicked
        tfOutros.setEnabled(false);
        ticket.setProblema("Ansiedade");
    }//GEN-LAST:event_jAnsiedadeMouseClicked

    private void jAnsiedadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnsiedadeActionPerformed

    }//GEN-LAST:event_jAnsiedadeActionPerformed

    private void jDrepressaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDrepressaoMouseClicked
        tfOutros.setEnabled(false);
        ticket.setProblema("Depressão");
    }//GEN-LAST:event_jDrepressaoMouseClicked

    private void jDrepressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrepressaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDrepressaoActionPerformed

    private void rOutrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rOutrosMouseClicked
        if (rOutros.isSelected()) {
            tfOutros.setEnabled(true);
        }
    }//GEN-LAST:event_rOutrosMouseClicked

    private void rOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rOutrosActionPerformed

    }//GEN-LAST:event_rOutrosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContatoActionPerformed

    public void atualizarCampos(){
        tfAssunto.setText(ticket.getAssunto());
        tfMensagem.setText(ticket.getMensagem());
        
        this.usuario = usuario;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTicketEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTicketEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTicketEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTicketEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTicketEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Assunto;
    private javax.swing.JLabel Assunto1;
    private javax.swing.JButton Enviar1;
    private javax.swing.JRadioButton jAnsiedade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jContador;
    private javax.swing.JRadioButton jDrepressao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rOutros;
    private javax.swing.JTextField tfAssunto;
    private javax.swing.JTextField tfContato;
    private javax.swing.JTextArea tfMensagem;
    private javax.swing.JTextField tfOutros;
    // End of variables declaration//GEN-END:variables
}

